---
abstract: 'Find code that runs in compile-time blocks'
author:
  - 'Erin Schoenhals <erin@cpanel.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Critic-Policy-CompileTime
no_index:
  directory:
    - t
    - inc
requires:
  PPI: '0'
  Perl::Critic: '0'
version: '0.02'
